# Generated by Django 5.2.8 on 2025-12-04 11:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "tax_rate",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "0%"),
                            (5, "5%"),
                            (12, "12%"),
                            (18, "18%"),
                            (28, "28%"),
                        ],
                        default=18,
                    ),
                ),
                ("is_service", models.BooleanField(default=False)),
                ("is_digital", models.BooleanField(default=False)),
                ("is_bundle", models.BooleanField(default=False)),
                ("track_stock", models.BooleanField(default=True)),
                (
                    "default_warehouse",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("reorder_level", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("isbn", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("PB", "Paperback"),
                            ("HB", "Hardcover"),
                            ("SB", "Softbound"),
                            ("EB", "Ebook"),
                            ("DB", "Digital Bundle"),
                        ],
                        default="PB",
                        max_length=3,
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("pages", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_grams", models.PositiveIntegerField(blank=True, null=True)),
                ("dimensions", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "class_grade",
                    models.CharField(
                        choices=[
                            ("LKG", "LKG"),
                            ("UKG", "UKG"),
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 10"),
                            ("11", "Class 11"),
                            ("12", "Class 12"),
                            ("ALL", "All Grades / General"),
                        ],
                        default="ALL",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "digital_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="digital_products/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "epub", "mobi", "zip"]
                            )
                        ],
                    ),
                ),
                ("digital_license_info", models.TextField(blank=True, null=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("BOOK", "Book"),
                            ("SET", "Set / Bundle"),
                            ("DIGITAL", "Digital"),
                            ("OTHER", "Other"),
                        ],
                        default="BOOK",
                        max_length=10,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "bundle_items",
                    models.ManyToManyField(
                        blank=True, related_name="bundled_in", to="catalog.product"
                    ),
                ),
            ],
            options={
                "ordering": ["sku", "name"],
            },
        ),
        migrations.CreateModel(
            name="PrintRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_no", models.CharField(blank=True, max_length=120, null=True)),
                ("printed_qty", models.PositiveIntegerField(default=0)),
                ("received_qty", models.PositiveIntegerField(default=0)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("print_date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_runs",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["print_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="BookSetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "book_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_of_sets",
                        to="catalog.product",
                    ),
                ),
                (
                    "set_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_items",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "manager_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "opening_hours",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="catalog_war_name_a33ad5_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="StockLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("in_qty", models.IntegerField(default=0)),
                ("out_qty", models.IntegerField(default=0)),
                ("balance", models.IntegerField(default=0)),
                ("ref_type", models.CharField(max_length=50)),
                ("ref_id", models.IntegerField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "print_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.printrun",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_ledgers",
                        to="catalog.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="printrun",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="catalog_pro_sku_2c4c34_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["isbn"], name="catalog_pro_isbn_c9d90a_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["class_grade"], name="catalog_pro_class_g_13e8b5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="booksetitem",
            unique_together={("set_product", "book_product")},
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(
                fields=["product", "warehouse", "date"],
                name="catalog_sto_product_c38fc4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockledger",
            index=models.Index(
                fields=["ref_type", "ref_id"], name="catalog_sto_ref_typ_f8b9e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="printrun",
            index=models.Index(
                fields=["product", "warehouse"], name="catalog_pri_product_eda60a_idx"
            ),
        ),
    ]
