# Generated by Django 5.2.8 on 2026-06-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
