# Generated by Django 5.2.8 on 2026-06-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_invoiceitem_hsn_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="bank_account_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="bank_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="manual_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="signatory_name",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
