# Generated by Django 5.2.8 on 2026-07-28 13:07

from django.db import migrations, models


def set_existing_default(apps, schema_editor):
    CompanyProfile = apps.get_model("sales", "CompanyProfile")
    first = CompanyProfile.objects.order_by("pk").first()
    if first:
        first.is_default = True
        first.save(update_fields=["is_default"])


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_salesreturn_salesreturnitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="invoice_prefix",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="invoice_terms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="legal_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="pan",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="state_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(set_existing_default, migrations.RunPython.noop),
    ]
